[env]
platform = ststm32
board = nucleo_h745zi_q
framework = cmsis
build_flags = -std=c11 -Wall -Wextra -D CORE_CM7
board_build.ldscript = $PROJECT_DIR/system/h745cm7_flash.ld
board_build.cmsis.startup_file = broken_path
board_build.cmsis.system_file = broken_path
monitor_speed = 115200
test_speed = 115200
test_framework = custom
[env:hello_led]
build_type = debug
build_src_filter = +<$PROJECT_DIR/system/*.c>
  +<$PROJECT_DIR/system/*.s>
  +<*>
