[platformio] ; глобальные параметры
description = "Hello World Example"
[env]
platform = native ; ПО для хост-компьютера
build_flags = -O0
  -std=c11 ; стандарт С11
  -Wall ; вывод всех предупреждений компилятора

[env:helloworld] ; окружение для программы hello world
build_type = debug ; включить символы отладки
build_src_filter = +<helloworld/*.c> ; папка с исходными кодами /src/helloworld
test_framework = custom
debug_test = native/*
check_tool = cppcheck
check_flags = cppcheck:--enable=all
  --suppress=unusedFunction
  --suppress=unmatchedSuppression
  --addon=<misra/misra.json>
check_src_filters =
  +<src/helloworld/*.c>
  +<lib/dynlist/src/*.c>
