[platformio]
description="Lab3 begin example project"
default_envs = blinker

[env]
platform = ststm32
board = nucleo_h745zi_q
framework = cmsis
monitor_speed = 115200
build_flags = -std=c11 -Wall -Wextra -D CORE_CM7 -D HSE_VALUE=8000000
board_build.cmsis.system_file = ignore
board_build.cmsis.startup_file = ignore

[env:blinker]
build_src_filter = +<$PROJECT_DIR/system/*.c>
                   +<$PROJECT_DIR/system/*.s>
                   +<blinker/*.c>
build_type = debug
build_flags = ${env.build_flags} -DVECT_TAB_SRAM
board_build.ldscript = $PROJECT_DIR/system/stm32h745xx_sram1_CM7.ld
debug_init_break = tbreak Reset_Handler
debug_init_cmds =
  target extended-remote $DEBUG_PORT
  $LOAD_CMDS
  $INIT_BREAK

[env:bootloader]
build_type = debug
build_src_filter = +<$PROJECT_DIR/system/*.c>
                   +<$PROJECT_DIR/system/*.s>
                   +<bootloader/*.c> 
                   +<lib/**>
board_build.ldscript = system/h745cm7_flash.ld
board_build.cmsis.startup_file = ignore
board_build.cmsis.system_file = ignore